football:
  target: dev

  outputs:
    dev:
      type: postgres
      host: host.docker.internal
      port: 5434
      user: pipeline
      password: pipeline
      dbname: football_dwh
      schema: public
      threads: 2